ALTER TABLE `order_line` ADD COLUMN IF NOT EXISTS 	`id` int AUTO_INCREMENT NOT NULL UNIQUE;
ALTER TABLE `order_line` ADD COLUMN IF NOT EXISTS 	`id_product` int NOT NULL;
ALTER TABLE `order_line` ADD COLUMN IF NOT EXISTS 	`quantity` int;
ALTER TABLE `order_line` ADD COLUMN IF NOT EXISTS 	`id_order` int NOT NULL;
ALTER TABLE `order_line` ADD COLUMN IF NOT EXISTS 	`created_at` datetime NOT NULL;
ALTER TABLE `order_line` ADD COLUMN IF NOT EXISTS 	`modified_at` datetime NOT NULL;
ALTER TABLE `order_line` ADD COLUMN IF NOT EXISTS 	`deleted_at` datetime NOT NULL;
ALTER TABLE `order` ADD COLUMN IF NOT EXISTS 	`id` int AUTO_INCREMENT NOT NULL UNIQUE;
ALTER TABLE `order` ADD COLUMN IF NOT EXISTS 	`id_user` int NOT NULL;
ALTER TABLE `order` ADD COLUMN IF NOT EXISTS 	`created_at` datetime NOT NULL;
ALTER TABLE `order` ADD COLUMN IF NOT EXISTS 	`modified_at` datetime NOT NULL;
ALTER TABLE `order` ADD COLUMN IF NOT EXISTS 	`deleted_at` datetime NOT NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS 	`id` int AUTO_INCREMENT NOT NULL UNIQUE;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS 	`email` varchar(255) NOT NULL UNIQUE;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS 	`password` varchar(255) NOT NULL;
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS 	`name` varchar(255);
ALTER TABLE `users` ADD COLUMN IF NOT EXISTS 	`created_at` datetime NOT NULL;
ALTER TABLE `artisans` ADD COLUMN IF NOT EXISTS 	`id` int AUTO_INCREMENT NOT NULL UNIQUE;
ALTER TABLE `artisans` ADD COLUMN IF NOT EXISTS 	`name` varchar(255) NOT NULL;
ALTER TABLE `artisans` ADD COLUMN IF NOT EXISTS 	`address` varchar(255) NOT NULL;
ALTER TABLE `artisans` ADD COLUMN IF NOT EXISTS 	`rib` varchar(255) NOT NULL;
ALTER TABLE `artisans` ADD COLUMN IF NOT EXISTS 	`id_user` int NOT NULL;
ALTER TABLE `artisans` ADD COLUMN IF NOT EXISTS 	`created_at` datetime NOT NULL;
ALTER TABLE `artisans` ADD COLUMN IF NOT EXISTS 	`modified_at` datetime NOT NULL;
ALTER TABLE `artisans` ADD COLUMN IF NOT EXISTS 	`deleted_at` datetime;
ALTER TABLE `artisans` ADD COLUMN IF NOT EXISTS 	`description` varchar(255) NOT NULL;
ALTER TABLE `products` ADD COLUMN IF NOT EXISTS 	`created_at` datetime;
ALTER TABLE `products` ADD COLUMN IF NOT EXISTS 	`modified_at` datetime;
ALTER TABLE `products` ADD COLUMN IF NOT EXISTS 	`id` int AUTO_INCREMENT NOT NULL UNIQUE;
ALTER TABLE `products` ADD COLUMN IF NOT EXISTS 	`artisan_id` int;
ALTER TABLE `products` ADD COLUMN IF NOT EXISTS 	`name` varchar(255);
ALTER TABLE `products` ADD COLUMN IF NOT EXISTS 	`description` text;
ALTER TABLE `products` ADD COLUMN IF NOT EXISTS 	`price` float;
ALTER TABLE `products` ADD COLUMN IF NOT EXISTS 	`image` varchar(255);